name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3.'
inputs:
  bucket:
    description: 'The S3 bucket name'
    required: true 
  bucket-region:
    description: 'The region of the S3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the deployable files.'
    required: true
  role-arn:
    description: 'The ARN of the IAM role to assume'
    required: true
  oidc-audience:
    description: ''
    required: false
    default: 'sts.amazonaws.com'
runs:
  using: 'node16'
  main: 'main.js'